# Debian-based Node image
FROM node:20-bullseye-slim

# Install ps and other minimal tools
RUN apt-get update && apt-get install -y procps && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

RUN npx prisma generate

EXPOSE 3000
CMD ["npm", "run", "start:dev"]
