version: '3.8'

services:
  postgres:
    image: postgres:16
    restart: always
    container_name: music-postgres
    environment:
      POSTGRES_USER: musicplaylistadmin
      POSTGRES_PASSWORD: 4HcK94qXyZOilMWV
      POSTGRES_DB: music_playlist
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./music-playlist-api   # ✅ fixed folder name
    container_name: music-backend
    ports:
      - "3030:3000"
    environment:
      DATABASE_URL: postgresql://musicplaylistadmin:4HcK94qXyZOilMWV@postgres:5432/music_playlist?schema=public
      PORT: 3000
    depends_on:
      - postgres

  frontend:
    build:
      context: ./music-playlist       # ✅ fixed folder name
    container_name: music-frontend
    ports:
      - "8080:8080"
    environment:
      BACKEND_URL: http://localhost:3030
      NEXT_PUBLIC_BACKEND_URL: http://localhost:3030
    depends_on:
      - backend

volumes:
  postgres_data:
